jdbc:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    user: root
    password: 123456
    jdbcUrl: jdbc:mysql://localhost:3306/crm
    maxPoolSize: 100
    minPoolSize: 10
    initialPoolSize: 10


spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /
      suffix: .jsp
  aop:
    auto: true
    proxy-target-class: true
  redis:
    port: 8888


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.crazycode.pojo
  mapper-locations: classpath:com/crazycode/mapper/*.xml

pagehelper:
  reasonable: true
  auto-dialect: mysql


shiro:
  loginUrl: /login.jsp
  successUrl: /pages/main.jsp
  unauthorizedUrl: /403.jsp
